function idxs = FindProminentPeak4D(hist, width, mode)
%Troba les coordenades on el m�xim de pixels dins un cub 3x3x3 que recorre
%lhistograma es troba a al pla centre horitzontal.
%widht=1 i mode=2

peaks = [];

for i = width+1:size(hist, 1)-width
    for j = width+1:size(hist, 2)-width
        for k = width+1:size(hist, 3)-width
%fa un escombrat de tot l'histograma, en matrius de 3x3x3 enganxat el valor
%m�s alt del cub i en guarda l'�ndex. Si l'index es el del mig el guarda.
            pattern = hist([i - width i i + width], [j - width j j + width], [k - width k k + width]);
            
            [~, ind] = max(max(max(hist(i-width:i+width, j-width:i+width, k-width:k+width))));
            
            switch(mode)
                case 1
                    % Behind and infront points
                    val = 7*pattern(2, 2, 2) - ...
                            pattern(2, 2, 1) - ...
                            pattern(2, 2, 3) - ...
                            pattern(1, 2, 2) - ...
                            pattern(2, 1, 2) - ...
                            pattern(2, 3, 2) - ...
                            pattern(3, 2, 2);
                case 2
                    % Above and below points
                    val = 6*pattern(2, 2, 2) - ...
                            pattern(2, 2, 1) - ...
                            pattern(2, 2, 3) - ...
                            pattern(1, 2, 2) - ...
                            pattern(2, 1, 2) - ...
                            pattern(2, 3, 2) - ...
                            pattern(3, 2, 2);
                case 3
                    % Left and right points
                    val = 5*pattern(2, 2, 2) - ...
                            pattern(2, 2, 1) - ...
                            pattern(2, 2, 3) - ...
                            pattern(1, 2, 2) - ...
                            pattern(2, 1, 2) - ...
                            pattern(2, 3, 2) - ...
                            pattern(3, 2, 2);
                case 4
                    % Cross points
                    val = 4*pattern(2, 2, 2) - ...
                            pattern(2, 2, 1) - ...
                            pattern(2, 2, 3) - ...
                            pattern(1, 2, 2) - ...
                            pattern(2, 1, 2) - ...
                            pattern(2, 3, 2) - ...
                            pattern(3, 2, 2);

            end
            
            if((ind == width*3 - 1))
                peaks = [peaks; [i, j, k, val]];
            end
        end
    end
end

idxs = peaks;

end